name: meet
description: A new Flutter project.

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^6.0.0
  equatable: ^1.2.3
  fluro: ^1.7.8
  flutter_bloc: ^6.0.0
  flutter_fortune_wheel: ^0.2.2
  flutter_hooks: ^0.15.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  provider: ^4.1.3
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
