name: meet
description: A new Flutter project.

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^6.0.0
#  calendar_service:
#    path: packages/calendar_service.dart
  equatable: ^1.2.3
  fluro: ^1.7.8
  flutter_bloc: ^6.0.0
  flutter_duration_picker: ^1.0.4
  flutter_fortune_wheel: ^0.0.8
  flutter_hooks: ^0.15.0
  flutter_svg: ^0.19.2+1
  provider: ^4.1.3
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
