import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

// Generated by http://mcg.mbitson.com/
// Adjusted with https://materialpalettes.com/
// Selected with https://color.joelb.dev/hsl/162/100/33
class KevlatusColors {
  static const MaterialColor mint =
      MaterialColor(_mintPrimaryValue, <int, Color>{
    50: Color(0xFFE0F4EE),
    100: Color(0xFFB3E5D6),
    200: Color(0xFF80D3BA),
    300: Color(0xFF4DC19E),
    400: Color(0xFF26B48A),
    500: Color(_mintPrimaryValue),
    600: Color(0xFF009F6D),
    700: Color(0xFF009662),
    800: Color(0xFF008C58),
    900: Color(0xFF007C45),
  });
  static const int _mintPrimaryValue = 0xFF00A775;

  static const MaterialColor mintAccent =
      MaterialColor(_mintAccentValue, <int, Color>{
    100: Color(0xFFA9FFD3),
    200: Color(_mintAccentValue),
    400: Color(0xFF43FF9E),
    700: Color(0xFF2AFF91),
  });
  static const int _mintAccentValue = 0xFF76FFB9;

  static const MaterialColor mintDark =
      MaterialColor(_mintdarkPrimaryValue, <int, Color>{
    50: Color(0xFFF0FAF7),
    100: Color(0xFFD9F2EA),
    200: Color(0xFFC0E9DD),
    300: Color(0xFFA6E0CF),
    400: Color(0xFF93DAC4),
    500: Color(_mintdarkPrimaryValue),
    600: Color(0xFF78CEB3),
    700: Color(0xFF6DC8AB),
    800: Color(0xFF63C2A3),
    900: Color(0xFF50B794),
  });
  static const int _mintdarkPrimaryValue = 0xFF80D3BA;

  static const MaterialColor mintAccentDark =
      MaterialColor(_mintdarkAccentValue, <int, Color>{
    100: Color(0xFFFFFFFF),
    200: Color(_mintdarkAccentValue),
    400: Color(0xFFB1FFE3),
    700: Color(0xFF97FFDA),
  });
  static const int _mintdarkAccentValue = 0xFFE4FFF5;

  static const MaterialColor gold =
      MaterialColor(_goldPrimaryValue, <int, Color>{
    50: Color(0xFFF5EFE0),
    100: Color(0xFFE5D6B3),
    200: Color(0xFFD4BB80),
    300: Color(0xFFC29F4D),
    400: Color(0xFFB58B26),
    500: Color(_goldPrimaryValue),
    600: Color(0xFFA06E00),
    700: Color(0xFF976300),
    800: Color(0xFF8D5900),
    900: Color(0xFF7D4600),
  });
  static const int _goldPrimaryValue = 0xFFA87600;

  static const MaterialColor goldAccent =
      MaterialColor(_goldAccentValue, <int, Color>{
    100: Color(0xFFFFD4AA),
    200: Color(_goldAccentValue),
    400: Color(0xFFFFA044),
    700: Color(0xFFFF932A),
  });
  static const int _goldAccentValue = 0xFFFFBA77;

  static const MaterialColor goldDark =
      MaterialColor(_golddarkPrimaryValue, <int, Color>{
    50: Color(0xFFFAF7F0),
    100: Color(0xFFF2EBD9),
    200: Color(0xFFEADDC0),
    300: Color(0xFFE1CFA6),
    400: Color(0xFFDAC593),
    500: Color(_golddarkPrimaryValue),
    600: Color(0xFFCFB578),
    700: Color(0xFFC9AC6D),
    800: Color(0xFFC3A463),
    900: Color(0xFFB99650),
  });
  static const int _golddarkPrimaryValue = 0xFFD4BB80;

  static const MaterialColor goldAccentDark =
      MaterialColor(_golddarkAccentValue, <int, Color>{
    100: Color(0xFFFFFFFF),
    200: Color(_golddarkAccentValue),
    400: Color(0xFFFFE4B3),
    700: Color(0xFFFFDB99),
  });
  static const int _golddarkAccentValue = 0xFFFFF6E5;

  static const MaterialColor purple =
      MaterialColor(_purplePrimaryValue, <int, Color>{
    50: Color(0xFFEFE0F5),
    100: Color(0xFFD6B3E5),
    200: Color(0xFFBB80D4),
    300: Color(0xFF9F4DC2),
    400: Color(0xFF8B26B5),
    500: Color(_purplePrimaryValue),
    600: Color(0xFF6E00A0),
    700: Color(0xFF630097),
    800: Color(0xFF59008D),
    900: Color(0xFF46007D),
  });
  static const int _purplePrimaryValue = 0xFF7600A8;

  static const MaterialColor purpleAccent =
      MaterialColor(_purpleAccentValue, <int, Color>{
    100: Color(0xFFD4AAFF),
    200: Color(_purpleAccentValue),
    400: Color(0xFFA044FF),
    700: Color(0xFF932AFF),
  });
  static const int _purpleAccentValue = 0xFFBA77FF;

  static const MaterialColor purpledark =
      MaterialColor(_purpledarkPrimaryValue, <int, Color>{
    50: Color(0xFFF7F0FA),
    100: Color(0xFFEBD9F2),
    200: Color(0xFFDDC0EA),
    300: Color(0xFFCFA6E1),
    400: Color(0xFFC593DA),
    500: Color(_purpledarkPrimaryValue),
    600: Color(0xFFB578CF),
    700: Color(0xFFAC6DC9),
    800: Color(0xFFA463C3),
    900: Color(0xFF9650B9),
  });
  static const int _purpledarkPrimaryValue = 0xFFBB80D4;

  static const MaterialColor purpleAccentDark =
      MaterialColor(_purpledarkAccentValue, <int, Color>{
    100: Color(0xFFFFFFFF),
    200: Color(_purpledarkAccentValue),
    400: Color(0xFFE4B3FF),
    700: Color(0xFFDB99FF),
  });
  static const int _purpledarkAccentValue = 0xFFF6E5FF;

  static const MaterialColor blue =
      MaterialColor(_bluePrimaryValue, <int, Color>{
    50: Color(0xFFE0E6F5),
    100: Color(0xFFB3C2E5),
    200: Color(0xFF8099D4),
    300: Color(0xFF4D70C2),
    400: Color(0xFF2651B5),
    500: Color(_bluePrimaryValue),
    600: Color(0xFF002DA0),
    700: Color(0xFF002697),
    800: Color(0xFF001F8D),
    900: Color(0xFF00137D),
  });
  static const int _bluePrimaryValue = 0xFF0032A8;

  static const MaterialColor blueAccent =
      MaterialColor(_blueAccentValue, <int, Color>{
    100: Color(0xFFAAB1FF),
    200: Color(_blueAccentValue),
    400: Color(0xFF4453FF),
    700: Color(0xFF2A3CFF),
  });
  static const int _blueAccentValue = 0xFF7782FF;

  static const MaterialColor blueDark =
      MaterialColor(_bluedarkPrimaryValue, <int, Color>{
    50: Color(0xFFF0F3FA),
    100: Color(0xFFD9E0F2),
    200: Color(0xFFC0CCEA),
    300: Color(0xFFA6B8E1),
    400: Color(0xFF93A8DA),
    500: Color(_bluedarkPrimaryValue),
    600: Color(0xFF7891CF),
    700: Color(0xFF6D86C9),
    800: Color(0xFF637CC3),
    900: Color(0xFF506BB9),
  });
  static const int _bluedarkPrimaryValue = 0xFF8099D4;

  static const MaterialColor blueAccentDark =
      MaterialColor(_bluedarkAccentValue, <int, Color>{
    100: Color(0xFFFFFFFF),
    200: Color(_bluedarkAccentValue),
    400: Color(0xFFB3C5FF),
    700: Color(0xFF99B2FF),
  });
  static const int _bluedarkAccentValue = 0xFFE5ECFF;

  static const MaterialColor red = MaterialColor(_redPrimaryValue, <int, Color>{
    50: Color(0xFFF5E0E6),
    100: Color(0xFFE5B3C2),
    200: Color(0xFFD48099),
    300: Color(0xFFC24D70),
    400: Color(0xFFB52651),
    500: Color(_redPrimaryValue),
    600: Color(0xFFA0002D),
    700: Color(0xFF970026),
    800: Color(0xFF8D001F),
    900: Color(0xFF7D0013),
  });
  static const int _redPrimaryValue = 0xFFA80032;

  static const MaterialColor redAccent =
      MaterialColor(_redAccentValue, <int, Color>{
    100: Color(0xFFFFAAB1),
    200: Color(_redAccentValue),
    400: Color(0xFFFF4453),
    700: Color(0xFFFF2A3C),
  });
  static const int _redAccentValue = 0xFFFF7782;

  static const MaterialColor redDark =
      MaterialColor(_reddarkPrimaryValue, <int, Color>{
    50: Color(0xFFFAF0F3),
    100: Color(0xFFF2D9E0),
    200: Color(0xFFEAC0CC),
    300: Color(0xFFE1A6B8),
    400: Color(0xFFDA93A8),
    500: Color(_reddarkPrimaryValue),
    600: Color(0xFFCF7891),
    700: Color(0xFFC96D86),
    800: Color(0xFFC3637C),
    900: Color(0xFFB9506B),
  });
  static const int _reddarkPrimaryValue = 0xFFD48099;

  static const MaterialColor redAccentDark =
      MaterialColor(_reddarkAccentValue, <int, Color>{
    100: Color(0xFFFFFFFF),
    200: Color(_reddarkAccentValue),
    400: Color(0xFFFFB3C5),
    700: Color(0xFFFF99B2),
  });
  static const int _reddarkAccentValue = 0xFFFFE5EC;
}

final ThemeData lightTheme = ThemeData(
  visualDensity: VisualDensity.comfortable,
  primarySwatch: KevlatusColors.mint,
  primaryColor: KevlatusColors.mint,
  accentColor: KevlatusColors.goldAccent,
  brightness: Brightness.light,
);

final ThemeData darkTheme = ThemeData(
  visualDensity: VisualDensity.comfortable,
  primarySwatch: KevlatusColors.mintDark,
  primaryColor: KevlatusColors.mintDark,
  accentColor: KevlatusColors.goldAccent,
  brightness: Brightness.dark,
);
