import 'package:flutter/material.dart';

// Generated by http://mcg.mbitson.com/
class KevlatusColors {
  static const int _mintPrimaryValue = 0xFF3EB489;
  static const MaterialColor mint =
      MaterialColor(_mintPrimaryValue, <int, Color>{
    50: Color(0xFFE8F6F1),
    100: Color(0xFFC5E9DC),
    200: Color(0xFF9FDAC4),
    300: Color(0xFF78CBAC),
    400: Color(0xFF5BBF9B),
    500: Color(_mintPrimaryValue),
    600: Color(0xFF38AD81),
    700: Color(0xFF30A476),
    800: Color(0xFF289C6C),
    900: Color(0xFF1B8C59),
  });

  static const int _mintAccentValue = 0xFF92FFCB;
  static const MaterialColor mintAccent =
      MaterialColor(_mintAccentValue, <int, Color>{
    100: Color(0xFFC5FFE3),
    200: Color(_mintAccentValue),
    400: Color(0xFF5FFFB2),
    700: Color(0xFF46FFA6),
  });

  static const int _coralPrimaryValue = 0xFFFF7F50;
  static const MaterialColor coral =
      MaterialColor(_coralPrimaryValue, <int, Color>{
    50: Color(0xFFFFF0EA),
    100: Color(0xFFFFD9CB),
    200: Color(0xFFFFBFA8),
    300: Color(0xFFFFA585),
    400: Color(0xFFFF926A),
    500: Color(_coralPrimaryValue),
    600: Color(0xFFFF7749),
    700: Color(0xFFFF6C40),
    800: Color(0xFFFF6237),
    900: Color(0xFFFF4F27),
  });

  static const int _coralAccentValue = 0xFFFFFFFF;
  static const MaterialColor coralAccent =
      MaterialColor(_coralAccentValue, <int, Color>{
    100: Color(0xFFFFFFFF),
    200: Color(_coralAccentValue),
    400: Color(0xFFFFDBD4),
    700: Color(0xFFFFC6BB),
  });
}
