import 'package:flutter/material.dart';

// Generated by http://mcg.mbitson.com/
class KevlatusColors {
  static const MaterialColor mint =
      MaterialColor(_mintPrimaryValue, <int, Color>{
    50: Color(0xFFE0F4EE),
    100: Color(0xFFB3E5D6),
    200: Color(0xFF80D3BA),
    300: Color(0xFF4DC19E),
    400: Color(0xFF26B48A),
    500: Color(_mintPrimaryValue),
    600: Color(0xFF009F6D),
    700: Color(0xFF009662),
    800: Color(0xFF008C58),
    900: Color(0xFF007C45),
  });
  static const int _mintPrimaryValue = 0xFF00A775;

  static const MaterialColor mintAccent =
      MaterialColor(_mintAccentValue, <int, Color>{
    100: Color(0xFFA9FFD3),
    200: Color(_mintAccentValue),
    400: Color(0xFF43FF9E),
    700: Color(0xFF2AFF91),
  });
  static const int _mintAccentValue = 0xFF76FFB9;

  static const MaterialColor purple =
      MaterialColor(_purplePrimaryValue, <int, Color>{
    50: Color(0xFFF3E8F7),
    100: Color(0xFFE0C6EB),
    200: Color(0xFFCBA1DD),
    300: Color(0xFFB67BCF),
    400: Color(0xFFA75EC5),
    500: Color(_purplePrimaryValue),
    600: Color(0xFF8F3CB5),
    700: Color(0xFF8433AC),
    800: Color(0xFF7A2BA4),
    900: Color(0xFF691D96),
  });
  static const int _purplePrimaryValue = 0xFF9742BB;

  static const MaterialColor purpleAccent =
      MaterialColor(_purpleAccentValue, <int, Color>{
    100: Color(0xFFECCFFF),
    200: Color(_purpleAccentValue),
    400: Color(0xFFC369FF),
    700: Color(0xFFB950FF),
  });
  static const int _purpleAccentValue = 0xFFD89CFF;

  static const MaterialColor mintForDark =
      MaterialColor(_mintForDarkValue, <int, Color>{
    50: Color(0xFFF0FAF7),
    100: Color(0xFFD9F2EA),
    200: Color(0xFFC0E9DD),
    300: Color(0xFFA6E0CF),
    400: Color(0xFF93DAC4),
    500: Color(_mintForDarkValue),
    600: Color(0xFF78CEB3),
    700: Color(0xFF6DC8AB),
    800: Color(0xFF63C2A3),
    900: Color(0xFF50B794),
  });
  static const int _mintForDarkValue = 0xFF80D3BA;
}
