
name: Test on pull request
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3

      - name: Install dependencies
        run: npm ci

      #- name: Lint
      #  run: npm run lint

      # - name: Run tests
      #   run: npm run test -- --no-watch --browsers=ChromeHeadless
