name: Release (beta)
on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@master
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter config --enable-web

      - run: flutter pub get
      #      - run: flutter test --coverage

      #      - name: upload coverage to Coveralls
      #        uses: coverallsapp/github-action@master
      #        with:
      #          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build app
        run: flutter build web

      - name: Publish
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_DIR: build/web